set_project("dvdbchar")
set_version("0.1.0")

add_rules("mode.debug", "mode.release")
set_runtimes("MD") 
if is_mode("debug") then
    set_runtimes("MDd")
end

includes("xmake")

add_requires("dawn", {configs = {shared = true}})
add_requires("slang")
add_requires("spdlog")
add_requires("spout", {configs = {shared = true}})
add_requires("glfw")
add_requires("asio")
add_requires("oscpack")
add_requires("fastgltf")
add_requires("glm")
add_requires("simdjson")
add_requires("tl_expected")
add_requires("stdexec")
add_requires("range-v3")
add_requires("stb")
add_requires("rtmidi")
add_requires("opencv 4.12.0")
add_requires("nlohmann_json")

target("dvdbchar.slang.lib")
    set_kind("static")
    add_packages("slang")
    add_rules("slang", {target_kind = "none"})
    add_files("src/slang/Uniform.slang")

target("dvdbchar.slang")
    set_kind("static")
    add_packages("slang")
    add_deps("dvdbchar.slang.lib")
    add_rules("slang", {target_kind = "wgsl"})
    add_files("src/slang/Pipeline.slang")
    
target("dvdbchar")
    set_kind("binary")
    set_languages("cxx20")
    add_rules("utils.bin2c", {extensions = {".wgsl", ".json"}})

    add_deps("dvdbchar.slang")
    add_deps("dvdbchar.slang.lib")
    add_packages("dawn")
    add_packages("slang")
    add_packages("spdlog")
    add_deps("glfw3dawn")
    add_packages("spout")
    add_packages("glfw")
    add_packages("asio")
    add_packages("oscpack")
    add_packages("fastgltf")
    add_packages("glm")
    add_packages("stdexec")
    add_packages("simdjson")
    add_packages("tl_expected")
    add_packages("range-v3")
    add_packages("stb")
    add_packages("rtmidi")
    add_packages("opencv")
    add_packages("nlohmann_json")

    add_headerfiles("src/**.hpp")
    add_files("src/**.cpp")
    add_files("src/slang/**.wgsl")
    add_files("src/slang/**.refl.json")
    add_includedirs("src")

    if is_plat("windows") then
        add_defines("NOMINMAX")
    end

    -- add_installfiles("public/**", {prefixdir = "public"})
    -- add_installfiles("src/slang/**", {prefixdir = "shaders"})
    
    after_build(function(target)
        os.rm(path.join(target:targetdir(), "public"))
        os.rm(path.join(target:targetdir(), "shaders"))
        os.cp("public", path.join(target:targetdir(), "public"))
        os.cp("src/slang", path.join(target:targetdir(), "shaders"))
    end)

    after_install(function(target)
        os.rm(path.join(target:installdir(), "public"))
        os.rm(path.join(target:installdir(), "shaders"))
        os.cp("public", path.join(target:installdir(), "public"))
        os.cp("src/slang", path.join(target:installdir(), "shaders"))
    end)
